<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function bounce_handler_help($path, $arg) {
  switch ($path) {
    case 'admin/help#bounce_handler':
      $output = '<p>' . t('This module lists the incoming bounces for your website. It allows to disable a users mails to avoid producin more bounces.') . '</p>';
      return $output;
    case 'admin/reports/bounce_handler':
      return '<p>' . t('This list shows the most recent bounces. You can investigate the bounce by following the "see bounce" link and see all bounces for a particular address by following the "see all bounces" link.') . '</p>';
    case 'admin/reports/bounce_handler_top':
      return '<p>' . t('This list shows the mail addresses for which the most bounces were received. The relevant column to decide if to take action is the one listing hard bounces. A hard bounce indicates that the situation is currently beyond repair. You can see the affected mail address and to which user it belongs. You can see a list of all the bounces of a given mail address by following the "see bounces" link.')  . '</p>';
  }
}

/**
 * Implementation of hook_menu().
 */
function bounce_handler_menu() {
  $items['admin/settings/bounce_handler'] = array(
    'title' => 'Bounce handler settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bounce_handler_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'bounce_handler.admin.inc',
  );

  $items['admin/reports/bounce_handler'] = array(
    'title' => 'Recent incoming bounces',
    'description' => 'View incoming bounces.',
    'page callback' => 'bounce_handler_overview',
    'access arguments' => array('access site reports'),
    'file' => 'bounce_handler.admin.inc',
  );

  $items['admin/reports/bounce_handler_top'] = array(
    'title' => 'Bounce statistics',
    'description' => 'View bounce statistics.',
    'page callback' => 'bounce_handler_top',
    'access arguments' => array('access site reports'),
    'file' => 'bounce_handler.admin.inc',
  );

  $items['admin/reports/bounce/%'] = array(
    'title' => 'Details',
    'page callback' => 'bounce_handler_view_bounce',
    'page arguments' => array(3),
    'access arguments' => array('access site reports'),
    'type' => MENU_CALLBACK,
    'file' => 'bounce_handler.admin.inc',
  );

  $items['admin/reports/bounce_mail/%'] = array(
    'title' => 'Bounces per mail address',
    'page callback' => 'bounce_handler_view_bounce_address',
    'page arguments' => array(3),
    'access arguments' => array('access site reports'),
    'type' => MENU_CALLBACK,
    'file' => 'bounce_handler.admin.inc',
  );

  $items['user/%user/bounce_handler_mail_disable'] = array(
    'title' => 'Disable mails',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bounce_handler_disable_mails', 1),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    'type' => MENU_CALLBACK,
    'file' => 'bounce_handler.admin.inc',
  );


  return $items;
}

/**
 * Implementation of hook_user().
 */
function bounce_handler_user($op, &$edit, &$user) {
  if ($op == 'delete') {
    db_query('UPDATE {bounces} SET uid = 0 WHERE uid = %d', $user->uid);
  }
}

/**
 * Implementation of hook_cron().
 *
 * Remove expired bounce messages.
 */
function bounce_handler_cron() {
  // Cleanup the bounces table
  $max = db_result(db_query('SELECT MAX(bid) FROM {bounces}'));
  db_query('DELETE FROM {bounces} WHERE bid <= %d', $max - variable_get('bounce_handler_row_limit', 1000));
  // Remove stats without bounces
  $result = db_query('SELECT bs.sid FROM {bounce_statistics} bs LEFT JOIN {bounces} b ON bs.sid = b.sid WHERE b.sid IS NULL');
  while ($sid = db_fetch_object($result)) {
    db_query('DELETE FROM {bounce_statistics} WHERE sid = %d', $sid->sid);
  }
  // Recalculate stats
  $result = db_query('SELECT sid FROM {bounce_statistics}');
  while ($sid = db_fetch_object($result)) {
    db_query('UPDATE {bounce_statistics} SET count = (SELECT COUNT(*) FROM {bounces} WHERE sid = %d), remove = (SELECT COUNT(*) FROM {bounces} WHERE sid = %d AND severity = 1) WHERE sid = %d', $sid->sid, $sid->sid, $sid->sid);
  }
}

